#!/bin/bash

# $1 - script path
# $2 - she bang
create_type() {
  ensure-path-dir $1
  echo -e "$2\n\n" > $1
  chmod u+x #1
  vim +3 $1
}

# $1 - script type ("node" or "bash")
# $2 - script name
main() {
  ( [ "$1" == "node" ] &&
    create_type "$HOME/bin/node/$2" "#!/usr/bin/env node"
  ) || (
    [ "$1" == "bash" ] &&
    create_type "$HOME/bin/$2" "#!/bin/bash"
  )
}

main "$@"
